version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n

  redis:
    image: redis:6
    restart: always

  primary:
    build:
      context: .
      dockerfile: .railway/Primary.Dockerfile
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - QUEUE_MODE=redis
      - QUEUE_REDIS_HOST=redis
      - GENERIC_TIMEZONE=Europe/Madrid
    ports:
      - "5678:5678"
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: .
      dockerfile: .railway/Worker.Dockerfile
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - QUEUE_MODE=redis
      - QUEUE_REDIS_HOST=redis
      - GENERIC_TIMEZONE=Europe/Madrid
    depends_on:
      - postgres
      - redis
